---
title: "Collaboration"
description: |
  Major collaborative projects related to medications.
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

# Vanderbilt Specialty Pharmacy (VSP) Collaboration

## Projects Reports

<div class='font75'>

* Identifying Outcome Measures for Specialty Pharmacists in Rheumatoid Arthritis Using the Modified Delphi Method: [Delphi Method Project Report](https://choileena.github.io/collab_dir/2025-06-03 Delphi QR report.html)

* Specialty Pharmacy Curriculum Survey: [Specialty Pharmacy Curriculum Survey Project Report](https://choileena.github.io/collab_dir/CurriculumSurvery_QR.html)

* Neurology Pharmacist Intervention: [Neurology Pharmacist Intervention Project Report (Part II)](https://choileena.github.io/collab_dir/neuropin_newmod_aan 1.html)

* Impact of Race on Baseline Asthma Severity and Response to Biologic Therapy: [Asthma Project Report](https://choileena.github.io/collab_dir/asthma_allergy_abbreviated_report_v3.html)

* The impact of early oral anticancer medication monitoring through electronic patient assessments: [Oral Anticancer Medication Monitoring Project Report](https://choileena.github.io/collab_dir/ASHP Tech Grant QR report 1.html)

* Growth Hormone: [Growth Hormone Project Report (Part II)](https://choileena.github.io/collab_dir/Growthhormone_QR.html)

* PMN and TAT Comparison with External Specialty Pharmacies: [PMN and TAT Comparison Project Report](https://choileena.github.io/collab_dir/abbr_pmn_tat.html)

* MS Fumarates: [MS Fumarates Project Report](https://choileena.github.io/collab_dir/2024-05-15 MS Fumarates QR.html)

* Austedo Multisite-HD II: [Austedo Multisite-HD II Project Report](https://choileena.github.io/collab_dir/HD Austedo Multisite Stats Report.html)

* Pediatric Hepatitis C Patient Outcomes in a Tertiary Academic Medical Center Utilizing an Integrated Specialty Pharmacy Model (HSSP Study): [Pediatric Hepatitis C Patient Outcomes Project Report (HSSP Study)](https://choileena.github.io/collab_dir/HCV HSSP STATS QR.html)

* Pediatric Hepatitis C Patient Outcomes in a Tertiary Academic Medical Center Utilizing an Integrated Specialty Pharmacy Model (Cascade of Care): [Pediatric Hepatitis C Patient Outcomes Project Report (Cascade of Care)](https://choileena.github.io/collab_dir/HCV COC POSTER STATS.html)

* Tacrolimus Immediate-Release vs. Extended-Release Formulation Cost Analysis: [Transplant Cost Analysis Project Report](https://choileena.github.io/collab_dir/Transplant_Cost_Analysis_poster_report.html)

* Austedo Multisite Study for Huntington's Disease: [Austedo Multisite-HD Project Report](https://choileena.github.io/collab_dir/austedo-QR.html)

* Evaluating Patient-Reported Adherence and Outcomes in Specialty Disease States - A Dual Site Initiative: [Dual Site Project Project Report](https://choileena.github.io/collab_dir/dual-QR-report.html)

* MS Multisite Study Project: [MS Multisite Study Project Report](https://choileena.github.io/collab_dir/ms_multi-PRO-QR 2022.11.30.html)

* Health-System Specialty Pharmacies Ensure Patients Initiate New Oncology Treatments - A Multisite Study: [Vizient PMN Project Report](https://choileena.github.io/collab_dir/Vizient QR report.html)

* Financial Impact of Integrated Specialty Pharmacy Efforts to Avoid Oral Oncolytic Waste: [Onc Waste Avoidance Project Report](https://choileena.github.io/collab_dir/Onc_Waste_Avoidance_Poster.html)

* Use of Prescription Cannabidiol for the Management of Seizure Disorders at an Integrated Care Center: [Epidiolex Project II Report](https://choileena.github.io/collab_dir/epidiolex-QR2 2022.10.10b.html)

* Epidiolex Treatment for Lennox Gastaut Syndrome or Dravet Syndrome: [Epidiolex Project I Report ](https://choileena.github.io/collab_dir/Pharmacist management of prescription cannabidiol.html)

* Adherence Clinic Project: [Adherence Clinic Project Report](https://choileena.github.io/collab_dir/Specialty PharmD intervention targeting adherence.html)

* Assessing Patient-Reported Outcomes, Pharmacist Interventions, and Medication Adherence in Inflammatory Bowel Disease: [PRO in IBD Project Report](https://choileena.github.io/collab_dir/Patient-reported outcomes in an IBD clinic.html)

* Assessing Patient-Reported Outcomes, Pharmacist Interventions, and Medication Adherence in Multiple Sclerosis: [PRO in MS Project Report](https://choileena.github.io/collab_dir/Patient-reported outcomes and interventions in MS.html)

* Assessing Patient-Reported Outcomes, Pharmacist Interventions, and Medication Adherence in Dermatology and Asthma, Sinus, and Allergy Patients (ASAP): [PRO in ASAP Project Report](https://choileena.github.io/collab_dir/PROs in dermatology, asthma and allergy patients.html)

</div>
